name: 01 - Basic CI - Old

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show Node version
        run: node --version

      - name: Check JavaScript syntax
        run: node --check src/index.js
